name: If demo
on:
  push:
    branches:
      - main
      - develop

jobs:
  demo:
    # job 必须要有一个 runner
    runs-on: ubuntu-latest
    steps:
      - name: Run if branch is main
        if: github.ref_name == 'main'
        run: echo "Running for main branch"

      - name: Run another step
        run: echo "This step is running..."

      - name: Run developer step
        run: echo "just for a test"
