# 当有环境要输入的时候，只能是手动的，不能自动触发trigger

name: Inputs Demo
on:
  workflow_dispatch:
    inputs:
        environment:
          description: Choose the environment to deploy
          required: true
          default: dev
          type: choice
          # 选择要部署的环境
          options:
            - dev
            - prod
            - stage
            - test
        artifact_tags: 
          # 要求输入要部署的 APP 版本
          description: Choose the git tag app version to deploy
          required: true
jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the App
        run: echo "Deploying the App version ${{ inputs.artifact_tags }} to ${{ inputs.environment}}"

