name: Outputs Demo
on: push
jobs:
  # 这是一个 build job
  build:
    outputs:
      version: ${{ steps.step1.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: build step
        id: step1
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT

      - name: Step Two
        run: echo "This version is ${{ steps.step1.outputs.version }}"
  
  # 这是一个 deploy job
  deploy:
    # 依赖关系 依赖 build 完成
    needs: build
    # 每一个 job 都要有一个runner 如 ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the App
        run: |
          echo "We are deploying the app with version ${{ needs.build.outputs.version }}"




